version: '3'
services:
    client:
        image: react:app
        ports:
            - '3000:3000'
        depends_on:
            - api
        environment:
            - NODE_ENV=development
        stdin_open: true
        tty: true
    api:
        build: ./api
        ports:
            - '3001:3001'
    