version: '3'
services:
    client:
        image: webapp-client
        ports:
            - '8080:8080'
        depends_on:
            - api
        environment:
            - NODE_ENV=development
        stdin_open: true
        tty: true
    api:
        build: ./api
        ports:
            - '3001:3001'
    